# This file defines the Makefile variables that are used to compile
# the PHARCOS programs and  libraries. Edit this file as needed.

# The C compiler and compiler options.

CC		:= gcc
#CC		:= pgcc
CFLAGS		= -g -pg -O3
# CFLAGS	= -openmp -D_GNU_SOURCE -O3 -ipo -openmp-report0 #-gcc-version=400


# The Fortran 90 compiler and compiler options. Leave empty to
# disable Fortran 90 support.

F90 		:= gfortran -I../lib
#F90		:= pgf90 -g -pg -I../lib
#F90FLAGS	= -nofor-main -O3 
F90FLAGS	= -O3 
FFLAGS		= -O3
DEBUG_LEVEL	:= 1
DFLAGS		= -DCOMPILING_HOSTNAME=\"$(HOSTNAME)\" -DDEBUG_LEVEL=1 

# Search directories for include files and libraries.

INCLUDEDIR1	= ../include 
INCLUDEDIR2	= ../fish90/include 
INCLUDES	= -I $(INCLUDEDIR1) -I $(INCLUDEDIR2)
LIBDIRS		= 
INCDIRS		= 

# Command for creating static library.

AR		= ar -rcsv

# Other commands.

MV		= mv -f

